export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number;
  image: string;
  ram: string;
  storage: string;
  processor: string;
  battery: string;
  camera: string;
  display: string;
  rating: number;
  reviews: number;
  featured?: boolean;
  description: string;
}

export const products: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    price: 159900,
    originalPrice: 169900,
    image: "https://m.media-amazon.com/images/I/81Os1SDWpcL._SX679_.jpg",
    ram: "8GB",
    storage: "256GB",
    processor: "A17 Pro",
    battery: "4422 mAh",
    camera: "48MP + 12MP + 12MP",
    display: "6.7 inch Super Retina XDR OLED",
    rating: 4.8,
    reviews: 1250,
    featured: true,
    description: "The iPhone 15 Pro Max features a strong and lightweight titanium design, the powerful A17 Pro chip, and a pro camera system with a 5x Telephoto lens."
  },
  {
    id: "2",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    price: 129999,
    originalPrice: 139999,
    image: "https://m.media-amazon.com/images/I/71CXhVhpM0L._SX679_.jpg",
    ram: "12GB",
    storage: "512GB",
    processor: "Snapdragon 8 Gen 3",
    battery: "5000 mAh",
    camera: "200MP + 50MP + 12MP + 10MP",
    display: "6.8 inch Dynamic AMOLED 2X",
    rating: 4.7,
    reviews: 980,
    featured: true,
    description: "Galaxy S24 Ultra is the ultimate Galaxy experience, featuring a titanium exterior, a flat display, and the power of Galaxy AI."
  },
  {
    id: "3",
    name: "Google Pixel 8 Pro",
    brand: "Google",
    price: 106999,
    image: "https://m.media-amazon.com/images/I/81Os1SDWpcL._SX679_.jpg",
    ram: "12GB",
    storage: "128GB",
    processor: "Google Tensor G3",
    battery: "5050 mAh",
    camera: "50MP + 48MP + 48MP",
    display: "6.7 inch Super Actua OLED",
    rating: 4.6,
    reviews: 650,
    featured: true,
    description: "Pixel 8 Pro is the all-pro engineered by Google. It has a sleek design, powerful performance, and the best Pixel camera yet."
  },
  {
    id: "4",
    name: "OnePlus 12",
    brand: "OnePlus",
    price: 64999,
    originalPrice: 69999,
    image: "https://m.media-amazon.com/images/I/717Qo4MH97L._SX679_.jpg",
    ram: "12GB",
    storage: "256GB",
    processor: "Snapdragon 8 Gen 3",
    battery: "5400 mAh",
    camera: "50MP + 64MP + 48MP",
    display: "6.82 inch ProXDR AMOLED",
    rating: 4.5,
    reviews: 820,
    description: "The OnePlus 12 delivers a fast and smooth experience with its powerful processor, advanced cooling system, and ultra-fast charging."
  },
  {
    id: "5",
    name: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    price: 99999,
    image: "https://m.media-amazon.com/images/I/71CXhVhpM0L._SX679_.jpg",
    ram: "16GB",
    storage: "512GB",
    processor: "Snapdragon 8 Gen 3",
    battery: "5000 mAh",
    camera: "50MP + 50MP + 50MP + 50MP",
    display: "6.73 inch LTPO AMOLED",
    rating: 4.4,
    reviews: 410,
    description: "Xiaomi 14 Ultra brings a professional photography experience with its Leica optics and powerful performance."
  },
  {
    id: "6",
    name: "Nothing Phone (2)",
    brand: "Nothing",
    price: 39999,
    originalPrice: 44999,
    image: "https://m.media-amazon.com/images/I/717Qo4MH97L._SX679_.jpg",
    ram: "8GB",
    storage: "128GB",
    processor: "Snapdragon 8+ Gen 1",
    battery: "4700 mAh",
    camera: "50MP + 50MP",
    display: "6.7 inch LTPO OLED",
    rating: 4.3,
    reviews: 560,
    description: "Nothing Phone (2) features a unique transparent design, the Glyph Interface, and a clean Nothing OS experience."
  },
  {
    id: "7",
    name: "Vivo X100 Pro",
    brand: "Vivo",
    price: 89999,
    image: "https://m.media-amazon.com/images/I/61cwywLZR-L._SX679_.jpg",
    ram: "16GB",
    storage: "512GB",
    processor: "Dimensity 9300",
    battery: "5400 mAh",
    camera: "50MP + 50MP + 50MP",
    display: "6.78 inch LTPO AMOLED",
    rating: 4.5,
    reviews: 320,
    description: "Vivo X100 Pro offers exceptional camera capabilities co-engineered with ZEISS, along with top-tier performance."
  },
  {
    id: "8",
    name: "iPhone 15",
    brand: "Apple",
    price: 79900,
    image: "https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg",
    ram: "6GB",
    storage: "128GB",
    processor: "A16 Bionic",
    battery: "3349 mAh",
    camera: "48MP + 12MP",
    display: "6.1 inch Super Retina XDR OLED",
    rating: 4.7,
    reviews: 2100,
    featured: true,
    description: "iPhone 15 brings the Dynamic Island, a 48MP Main camera, and USB-C to a beautiful, durable design."
  },
  {
    id: "9",
    name: "Samsung Galaxy S23 FE",
    brand: "Samsung",
    price: 29999,
    originalPrice: 49999,
    image: "https://m.media-amazon.com/images/I/81Os1SDWpcL._SX679_.jpg",
    ram: "8GB",
    storage: "128GB",
    processor: "Exynos 2200",
    battery: "4500 mAh",
    camera: "50MP + 12MP + 8MP",
    display: "6.4 inch Dynamic AMOLED 2X",
    rating: 4.3,
    reviews: 1450,
    description: "Samsung Galaxy S23 FE delivers flagship-level performance with a stunning AMOLED display and versatile triple camera system at an accessible price."
  },
  {
    id: "10",
    name: "iPhone 14",
    brand: "Apple",
    price: 59900,
    originalPrice: 69900,
    image: "https://m.media-amazon.com/images/I/61cwywLZR-L._SX679_.jpg",
    ram: "6GB",
    storage: "128GB",
    processor: "A15 Bionic",
    battery: "3279 mAh",
    camera: "12MP + 12MP",
    display: "6.1 inch Super Retina XDR OLED",
    rating: 4.6,
    reviews: 3200,
    description: "iPhone 14 features an advanced camera system, Crash Detection, and all-day battery life in a sleek, durable design."
  },
  {
    id: "11",
    name: "Realme GT 6T",
    brand: "Realme",
    price: 22999,
    originalPrice: 27999,
    image: "https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg",
    ram: "8GB",
    storage: "128GB",
    processor: "Snapdragon 7+ Gen 3",
    battery: "5500 mAh",
    camera: "50MP + 2MP",
    display: "6.78 inch LTPO AMOLED",
    rating: 4.3,
    reviews: 890,
    description: "Realme GT 6T delivers top-tier performance with Snapdragon 7+ Gen 3, 5500 mAh battery, and a stunning 120Hz AMOLED display."
  },
  {
    id: "12",
    name: "Motorola Edge 50 Pro",
    brand: "Motorola",
    price: 29999,
    originalPrice: 35999,
    image: "https://m.media-amazon.com/images/I/717Qo4MH97L._SX679_.jpg",
    ram: "8GB",
    storage: "256GB",
    processor: "Snapdragon 7 Gen 3",
    battery: "4500 mAh",
    camera: "50MP + 13MP + 10MP",
    display: "6.7 inch pOLED 144Hz",
    rating: 4.2,
    reviews: 720,
    description: "Motorola Edge 50 Pro offers a premium experience with 144Hz pOLED display, 68W TurboPower charging, and versatile triple camera."
  },
  {
    id: "13",
    name: "iQOO 12",
    brand: "iQOO",
    price: 52999,
    originalPrice: 57999,
    image: "https://m.media-amazon.com/images/I/71CXhVhpM0L._SX679_.jpg",
    ram: "12GB",
    storage: "256GB",
    processor: "Snapdragon 8 Gen 3",
    battery: "5000 mAh",
    camera: "50MP + 64MP + 50MP",
    display: "6.78 inch LTPO AMOLED",
    rating: 4.5,
    reviews: 640,
    featured: true,
    description: "iQOO 12 is a performance beast with Snapdragon 8 Gen 3 chipset, 120W FlashCharge, and a stunning 144Hz AMOLED display."
  },
  {
    id: "14",
    name: "POCO F6 5G",
    brand: "Poco",
    price: 21999,
    originalPrice: 25999,
    image: "https://m.media-amazon.com/images/I/81Os1SDWpcL._SX679_.jpg",
    ram: "8GB",
    storage: "256GB",
    processor: "Snapdragon 8s Gen 3",
    battery: "5000 mAh",
    camera: "50MP + 8MP",
    display: "6.67 inch AMOLED 120Hz",
    rating: 4.3,
    reviews: 1100,
    description: "POCO F6 5G brings flagship-grade Snapdragon 8s Gen 3 power, 90W turbo charging, and a 120Hz AMOLED display at an incredible price."
  },
  {
    id: "15",
    name: "Samsung Galaxy A55 5G",
    brand: "Samsung",
    price: 27999,
    originalPrice: 39999,
    image: "https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg",
    ram: "8GB",
    storage: "128GB",
    processor: "Exynos 1480",
    battery: "5000 mAh",
    camera: "50MP + 12MP + 5MP",
    display: "6.6 inch Super AMOLED",
    rating: 4.4,
    reviews: 2300,
    description: "Samsung Galaxy A55 5G features a premium glass design with key Galaxy innovations, Super AMOLED display, and reliable triple camera."
  },
  {
    id: "16",
    name: "Oppo Reno 12 Pro 5G",
    brand: "Oppo",
    price: 36999,
    originalPrice: 40999,
    image: "https://m.media-amazon.com/images/I/71CXhVhpM0L._SX679_.jpg",
    ram: "12GB",
    storage: "256GB",
    processor: "Dimensity 7300-Energy",
    battery: "5000 mAh",
    camera: "50MP + 8MP + 2MP",
    display: "6.7 inch AMOLED 120Hz",
    rating: 4.2,
    reviews: 530,
    description: "Oppo Reno 12 Pro combines AI photography features, a sleek design, and 80W SUPERVOOC charging for a premium mid-range experience."
  },
  {
    id: "17",
    name: "Redmi Note 13 Pro+ 5G",
    brand: "Xiaomi",
    price: 24999,
    originalPrice: 31999,
    image: "https://m.media-amazon.com/images/I/717Qo4MH97L._SX679_.jpg",
    ram: "8GB",
    storage: "256GB",
    processor: "Dimensity 7200 Ultra",
    battery: "5000 mAh",
    camera: "200MP + 8MP + 2MP",
    display: "6.67 inch AMOLED 120Hz",
    rating: 4.4,
    reviews: 4500,
    description: "Redmi Note 13 Pro+ packs a jaw-dropping 200MP camera, 120W HyperCharge, IP68 water resistance, and a curved AMOLED display."
  },
  {
    id: "18",
    name: "OnePlus Nord CE 4",
    brand: "OnePlus",
    price: 24999,
    originalPrice: 27999,
    image: "https://m.media-amazon.com/images/I/61cwywLZR-L._SX679_.jpg",
    ram: "8GB",
    storage: "128GB",
    processor: "Snapdragon 7 Gen 3",
    battery: "5500 mAh",
    camera: "50MP + 8MP",
    display: "6.7 inch AMOLED 120Hz",
    rating: 4.3,
    reviews: 1870,
    description: "OnePlus Nord CE 4 offers a smooth AMOLED experience, 100W SUPERVOOC charging, and all-day 5500 mAh battery life."
  },
  {
    id: "19",
    name: "Samsung Galaxy Z Flip 5",
    brand: "Samsung",
    price: 89999,
    originalPrice: 109999,
    image: "https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg",
    ram: "8GB",
    storage: "256GB",
    processor: "Snapdragon 8 Gen 2",
    battery: "3700 mAh",
    camera: "12MP + 12MP",
    display: "6.7 inch Dynamic AMOLED 2X",
    rating: 4.4,
    reviews: 780,
    featured: true,
    description: "Samsung Galaxy Z Flip 5 features a larger Flex Window, a compact foldable design, and flagship Snapdragon performance."
  },
  {
    id: "20",
    name: "Samsung Galaxy Z Fold 5",
    brand: "Samsung",
    price: 154999,
    originalPrice: 184999,
    image: "https://m.media-amazon.com/images/I/61cwywLZR-L._SX679_.jpg",
    ram: "12GB",
    storage: "256GB",
    processor: "Snapdragon 8 Gen 2",
    battery: "4400 mAh",
    camera: "50MP + 12MP + 10MP",
    display: "7.6 inch Dynamic AMOLED 2X",
    rating: 4.5,
    reviews: 540,
    featured: true,
    description: "Galaxy Z Fold 5 is the ultimate foldable with a massive 7.6-inch inner screen, multi-window multitasking, and S Pen support."
  },
  {
    id: "21",
    name: "Realme 12 Pro+ 5G",
    brand: "Realme",
    price: 29999,
    originalPrice: 32999,
    image: "https://m.media-amazon.com/images/I/81Os1SDWpcL._SX679_.jpg",
    ram: "8GB",
    storage: "256GB",
    processor: "Snapdragon 7s Gen 2",
    battery: "5000 mAh",
    camera: "64MP + 8MP + 32MP",
    display: "6.7 inch AMOLED 120Hz",
    rating: 4.2,
    reviews: 620,
    description: "Realme 12 Pro+ 5G features a periscope telephoto camera for flagship-level zoom, Sony camera sensors, and premium curved display."
  },
  {
    id: "22",
    name: "Vivo V30 Pro",
    brand: "Vivo",
    price: 39999,
    originalPrice: 46999,
    image: "https://m.media-amazon.com/images/I/71CXhVhpM0L._SX679_.jpg",
    ram: "8GB",
    storage: "256GB",
    processor: "Dimensity 8200",
    battery: "5000 mAh",
    camera: "50MP + 50MP",
    display: "6.78 inch AMOLED 120Hz",
    rating: 4.3,
    reviews: 430,
    description: "Vivo V30 Pro is a portrait master co-engineered with ZEISS, featuring studio-quality lighting and Aura Light for stunning portraits."
  },
  {
    id: "23",
    name: "Motorola Razr 40 Ultra",
    brand: "Motorola",
    price: 69999,
    originalPrice: 89999,
    image: "https://m.media-amazon.com/images/I/717Qo4MH97L._SX679_.jpg",
    ram: "8GB",
    storage: "256GB",
    processor: "Snapdragon 8+ Gen 1",
    battery: "3800 mAh",
    camera: "12MP + 13MP",
    display: "6.9 inch pOLED 165Hz",
    rating: 4.1,
    reviews: 350,
    description: "Motorola Razr 40 Ultra features the largest external display on a flip phone, premium vegan leather design, and elegant flip phone experience."
  },
  {
    id: "24",
    name: "iPhone 13",
    brand: "Apple",
    price: 49900,
    originalPrice: 59900,
    image: "https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg",
    ram: "4GB",
    storage: "128GB",
    processor: "A15 Bionic",
    battery: "3240 mAh",
    camera: "12MP + 12MP",
    display: "6.1 inch Super Retina XDR OLED",
    rating: 4.6,
    reviews: 5400,
    description: "iPhone 13 features a bright Super Retina XDR display, Cinematic mode, advanced dual-camera system, and incredible battery life."
  },
  {
    id: "25",
    name: "iQOO Neo 9 Pro",
    brand: "iQOO",
    price: 29999,
    originalPrice: 36999,
    image: "https://m.media-amazon.com/images/I/61cwywLZR-L._SX679_.jpg",
    ram: "8GB",
    storage: "128GB",
    processor: "Snapdragon 8 Gen 2",
    battery: "5160 mAh",
    camera: "50MP + 8MP",
    display: "6.78 inch LTPO AMOLED 144Hz",
    rating: 4.4,
    reviews: 920,
    description: "iQOO Neo 9 Pro brings flagship Snapdragon 8 Gen 2 power with 120W FlashCharge, a 144Hz display, and immersive gaming experience."
  },
  {
    id: "26",
    name: "POCO X6 Pro 5G",
    brand: "Poco",
    price: 17999,
    originalPrice: 22999,
    image: "https://m.media-amazon.com/images/I/81Os1SDWpcL._SX679_.jpg",
    ram: "8GB",
    storage: "256GB",
    processor: "Dimensity 8300 Ultra",
    battery: "5000 mAh",
    camera: "64MP + 8MP + 2MP",
    display: "6.67 inch AMOLED 120Hz",
    rating: 4.2,
    reviews: 2700,
    description: "POCO X6 Pro 5G offers a flagship-grade Dimensity 8300 Ultra processor, 64MP OIS camera, and 67W turbo charging at an unbeatable price."
  },
  {
    id: "27",
    name: "Samsung Galaxy M55 5G",
    brand: "Samsung",
    price: 21999,
    originalPrice: 26999,
    image: "https://m.media-amazon.com/images/I/71CXhVhpM0L._SX679_.jpg",
    ram: "8GB",
    storage: "128GB",
    processor: "Snapdragon 7 Gen 1",
    battery: "5000 mAh",
    camera: "50MP + 8MP + 2MP",
    display: "6.7 inch Super AMOLED 120Hz",
    rating: 4.2,
    reviews: 1380,
    description: "Samsung Galaxy M55 5G delivers powerful performance with Snapdragon 7 Gen 1, 45W fast charging, and a vibrant Super AMOLED display."
  },
  {
    id: "28",
    name: "Redmi Note 13 Pro 5G",
    brand: "Xiaomi",
    price: 19999,
    originalPrice: 25999,
    image: "https://m.media-amazon.com/images/I/717Qo4MH97L._SX679_.jpg",
    ram: "8GB",
    storage: "128GB",
    processor: "Snapdragon 7s Gen 2",
    battery: "5100 mAh",
    camera: "200MP + 8MP + 2MP",
    display: "6.67 inch AMOLED 120Hz",
    rating: 4.3,
    reviews: 3600,
    description: "Redmi Note 13 Pro brings an incredible 200MP primary camera, 67W turbo charge, and IP54 water resistance at a mid-range price point."
  }
];

export const brands = ["Apple", "Samsung", "Google", "OnePlus", "Xiaomi", "Nothing", "Vivo", "Realme", "Motorola", "iQOO", "Poco", "Oppo"];
export const ramOptions = ["4GB", "6GB", "8GB", "12GB", "16GB"];
export const storageOptions = ["128GB", "256GB", "512GB"];
